# 生成前端 logo 资源（一次性脚本，可重复执行；从仓库根目录下任意位置运行均可）：
#   1) webui-src/public/logo.png       <- 仓库根 logo.png 原样复制（Vite 静态复制到构建产物根）
#   2) webui-src/public/favicon.png    <- 256px PNG（圆形裁切 logo 图，半透明底）
#   3) webui-src/public/favicon.svg    <- 内嵌 PNG base64 的 SVG（含品牌渐变圆底）
#   4) webui-src/src/assets/logo.ts    <- base64 内联（防 AstrBot iframe 嵌套下相对路径解析异常）
$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.Drawing

# 从当前目录向上找仓库根（含 logo.png 的目录）
$repo = Get-Location
while ($repo -and -not (Test-Path (Join-Path $repo "logo.png"))) {
    $parent = Split-Path -Parent $repo
    if (-not $parent -or $parent -eq $repo) { $repo = $null; break }
    $repo = $parent
}
if (-not $repo) { throw "找不到仓库根（包含 logo.png 的目录），请在本仓库任意子目录下运行" }
$root = Join-Path $repo "webui-src"
$srcLogo = Join-Path $repo "logo.png"
$outPublic = Join-Path $root "public"
$outAssets = Join-Path $root "src/assets"
New-Item -ItemType Directory -Force -Path $outPublic | Out-Null
New-Item -ItemType Directory -Force -Path $outAssets | Out-Null

# 1) 复制原始 logo.png 到 public（Vite 会原样复制到构建产物根）
Copy-Item -LiteralPath $srcLogo -Destination (Join-Path $outPublic "logo.png") -Force

# 2) System.Drawing 生成圆形裁切 + 缩放 PNG（用于 favicon / 内联）
$size = 256
$bmp = New-Object System.Drawing.Bitmap -ArgumentList ([int]$size), ([int]$size)
if (-not $bmp) { throw "Bitmap 构造失败" }
$g = [System.Drawing.Graphics]::FromImage($bmp)
$g.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias
$g.Clear([System.Drawing.Color]::Transparent)
$src = [System.Drawing.Bitmap]::FromFile($srcLogo)
$side = [Math]::Min($src.Width, $src.Height)
$sx = [int](($src.Width - $side) / 2)
$sy = [int](($src.Height - $side) / 2)
$rect = New-Object System.Drawing.Rectangle(0, 0, $size, $size)
$g.DrawImage($src, $rect, $sx, $sy, $side, $side, [System.Drawing.GraphicsUnit]::Pixel)
$g.Dispose()
$pngPath = Join-Path $outPublic "favicon.png"
$bmp.Save($pngPath, [System.Drawing.Imaging.ImageFormat]::Png)
$bmp.Dispose()
$src.Dispose()
Write-Host "==> 生成 favicon.png: $pngPath"

# 3) 生成 favicon.svg（内嵌 PNG base64 + 品牌渐变圆底）
$bytes = [System.IO.File]::ReadAllBytes($pngPath)
$b64 = [Convert]::ToBase64String($bytes)
$svg = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><defs><radialGradient id="g" cx="35%" cy="30%" r="80%"><stop offset="0%" stop-color="#ffb3d1"/><stop offset="100%" stop-color="#ff8fb3"/></radialGradient></defs><circle cx="32" cy="32" r="30" fill="url(#g)"/><image x="6" y="6" width="52" height="52" preserveAspectRatio="xMidYMid meet" href="data:image/png;base64,' + [string]$b64 + '"/></svg>'
$svgPath = Join-Path $outPublic "favicon.svg"
[System.IO.File]::WriteAllText($svgPath, $svg, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "==> 生成 favicon.svg: $svgPath"

# 4) 生成 src/assets/logo.ts（base64 内联）
$pngBytes = [System.IO.File]::ReadAllBytes($pngPath)
$pngB64 = [Convert]::ToBase64String($pngBytes)
# 注释用 ASCII，避免 PowerShell 5.1 无 BOM UTF-8 下的编码问题
$ts = "// AUTO-GENERATED by scripts/gen_logo_assets.ps1 - DO NOT EDIT.`n// logo.png inlined as base64 so <img src> / CSS url() work inside AstrBot iframe.`nexport const LOGO_DATA_URL = `"data:image/png;base64," + [string]$pngB64 + "`";`n"
$tsPath = Join-Path $outAssets "logo.ts"
[System.IO.File]::WriteAllText($tsPath, $ts, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "==> 生成 src/assets/logo.ts: $tsPath"
Write-Host "==> 全部 logo 资源生成完成"